### ISSUE TITLE
Problem seit ESP HOME 12,3

### ISSUE THREAD

**Issue by 21-Jailbraik-21** [thealkly/Gasmeter-esp8266#1]
`INFO ESPHome 2023.12.3
INFO Reading configuration /config/esphome/gas-ablese-sensor.yaml...
Failed config

binary_sensor.gpio: [source <unicode string>:45]
  
  Pin 5 is used in multiple places.
  platform: gpio
  id: internal_pulse_counter
  pin: 
    number: 5
    mode: 
      input: True
      pullup: True
      output: False
      open_drain: False
      pulldown: False
      analog: False
    inverted: False
  name: Live-Impuls
  filters: 
    - delayed_on: 150ms
  on_press: 
    - then: 
        - lambda: !lambda |-
            id(total_pulses1) += 1;
  disabled_by_default: False
sensor.pulse_counter: [source <unicode string>:93]
  
  Pin 5 is used in multiple places.
  platform: pulse_counter
  pin: 
    number: 5
    mode: 
      input: True
      output: False
      open_drain: False
      pullup: False
      pulldown: False
      analog: False
    inverted: False
  name: Pulse Counter
  icon: mdi:pulse
  disabled_by_default: False
  force_update: False
  unit_of_measurement: pulses/min
  accuracy_decimals: 2
  state_class: measurement
  count_mode: 
    rising_edge: INCREMENT
    falling_edge: DISABLE
  internal_filter: 13us
  update_interval: 60s`

**Comment by 21-Jailbraik-21** [comment]
Seit 12.3 kann ich kein Update mehr machen, weil ich eine Fehlermeldung bekomme.
Hast Du eien Lösung?
​
102 / 5.000
Übersetzungsergebnisse
Übersetzung
Since 12.3 I can no longer do an update because I get an error message.
Do you have a solution?

**Comment by Joppo67** [comment]
Hallo 21-Jailbraik-21, 

ich hab das gleiche Problem, den Grund habe habe ich wohl auch schon gefunden: https://next.esphome.io/changelog/2023.12.0.html#pin-reuse-validation

Mein "Workaround" ist, die Sektion "platform: pulse_counter" unter "Sensor:" auszukommentieren. 
Bisher habe ich noch keinen Weg gefunden, wie man den pulse_counter UND den Zähler "total_pulses" unter "binary_sensor:" gleichzeitig zum Laufen zu bringen. Es gibt zwar den Parameter "allow_other_uses", der funktioniert bei mir aber auch nicht.

Da ich in dem Thema "ESPHome" auch neu bin hoffe ich, dass es einen Wissenden gibt, der uns die Lösung sagt ;)

**Comment by thealkly** [comment]
Thanks for your feedback! 

I had a look at the code and the problem is as mentioned. 
After checking my stats of the working version, I think pulse couter is not really needed.
It even seems to give some misleading data according to my influx record for around 12 months. 

Therefore I just excluded the code section as mentioned from @Joppo67 

_German:_
Danke für euer Feedback auf Yt und hier!
Ich hatte einen Blick auf den Code und das Problem habt ihr hier ja bereits erwähnt. Keine doppelte Pin Nutzung mehr ab ESPHome 2023.12

Nachdem ich meine Statistiken meines Sensors überprüft habe, denke ich, dass der Pulse Couter nicht wirklich benötigt wird.
Es scheint sogar einige irreführende Daten nach meinem Datensatz für etwa 12 Monate zu geben. 

Deshalb habe ich @Joppo67 Workaround in den Code gepackt.
